export const SET_PHONES = 'SET_PHONES'
export const DELETE_PHONE = 'DELETE_PHONE'
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const FILTER_PHONE = 'FILTER_PHONE'
export const ADD_PHONE = 'ADD_PHONE'
